export const colors = {
  red:          '#C0392B',
  redDark:      '#922B21',
  redLight:     '#FADBD8',
  gold:         '#D4AC0D',
  goldLight:    '#FCF3CF',
  goldDark:     '#9A7D0A',
  cream:        '#FDF6EC',
  white:        '#FFFFFF',
  text:         '#2C2C2C',
  textMuted:    '#7B7B7B',
  textLight:    '#BDBDBD',
  border:       '#E8D5C4',
  borderLight:  '#F2E8DC',
  success:      '#1D9E75',
  successLight: '#E1F5EE',
  warning:      '#BA7517',
  warningLight: '#FCF3CF',
  danger:       '#C0392B',
  dangerLight:  '#FADBD8',
}